### ISSUE TITLE
进行dev和infer的时候，结果有问题

### ISSUE THREAD

**Issue by erichuazhou** [NLPInBLCU/BiaffineDependencyParsing#14]
在train中调用dev的结果是没有问题的，单独读取model进行dev和Infer的时候，结果全错。不知道是不是读取模型的步骤有问题。
@LiangsLi

**Comment by erichuazhou** [comment]
@LiangsLi

**Comment by LiangsLi** [comment]
@erichuazhou  不好意思，刚注意到这个 issue，我之前跑的时候是没有这个问题的，看您已经关闭这个 issue 了，不知道是否解决了，这个项目存在一些问题，但是短时间内没有人来维护，非常抱歉~

**Comment by erichuazhou** [comment]
是我自己的问题。您的代码在dev和Infer的时候没有问题。
