### ISSUE TITLE
关于graph_vocab.py文件中的输入文件'../dataset/graph_vocab.txt'的内容及其获取方式

### ISSUE THREAD

**Issue by Fourha** [NLPInBLCU/BiaffineDependencyParsing#15]
您好！请问`graph_vocab.py`文件中的输入文件`'../dataset/graph_vocab.txt'`，是如何获取的呢?
起初我以为是bert预训练模型中的`vocab.txt`,但是发现这个`graph_vocab.txt`文件应该至少还要包括语义依存分析的标签。
因此目前不清楚：1.`graph_vocab.txt`如何获取？2.`graph_vocab.txt`包含哪些内容？
希望您能解答，谢谢~

**Comment by LiangsLi** [comment]
你好，训练前需要执行 https://github.com/NLPInBLCU/BiaffineDependencyParsing/blob/master/build_deps_vocab.py 文件生成依存标签的 vocab，这个脚本会自动生成 graph_vocab.txt 文件

**Comment by LiangsLi** [comment]
另外这个项目加载数据的方式存在一些问题，但是我已经离开学校了，可能近期都没有时间维护，非常抱歉

**Comment by Fourha** [comment]
> 另外这个项目加载数据的方式存在一些问题，但是我已经离开学校了，可能近期都没有时间维护，非常抱歉

感谢回复，我近期想要实现一个语义依存分析的项目，在学习您的代码，虽然存在一些暂时没有看懂的部分，但还是受益匪浅，谢谢~
