### ISSUE TITLE
您好，请问您使用的数据集是什么，CTB-5？

### ISSUE THREAD

**Issue by ycanduxiyu** [NLPInBLCU/BiaffineDependencyParsing#5]
如果是CTB-5，那您是怎么用BERT的“字”向量来做的呢? 句法分析不是要先分词吗？

**Comment by LiangsLi** [comment]
目前我们仅支持**语义依存分析**，使用的数据集是[HIT-SCIR/SemEval-2016: SemEval-2016 Task 9: Chinese Semantic Dependency Parsing](https://github.com/HIT-SCIR/SemEval-2016)。如果需要支持句法依存分析，你可以手动修改后面解码部分或者直接借鉴斯坦福的实现[stanfordnlp](https://github.com/stanfordnlp/stanfordnlp/blob/master/stanfordnlp/models/common/chuliu_edmonds.py)，同时将语料处理为[CoNLL-U 格式](https://universaldependencies.org/format.html)即可。后续有时间我们会支持**句法依存分析**

**Comment by LiangsLi** [comment]
依存分析的输入数据是已经分好词的（无论是CTB还是PTB）。使用BERT做encoder的时候我们取每一个词对应的尾字（或者首字或者首尾拼接）作为这个词的表示，此时需要先获取词语的首尾idx
